### ISSUE TITLE
Problem with compile Libtiff

### ISSUE THREAD

**Issue by kittener** [Tricker-z/CoFuzz#9]
I encountered some problems when compiling libtiff
Firstly, set the CC and CXX
`export CC=/workspace/CoFuzz/third_party/concolic/qsym/symcc CXX=/workspace/CoFuzz/third_party/concolic/qsym/sym++`
Secondly, create the Makefile
`./configure --disable-shared`
Then, I compile it
`make -j4`

But it doesn't work, and the information is following:

libtool: compile:  /workspace/CoFuzz/third_party/concolic/qsym/symcc -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_aux.lo -MD -MP -MF .deps/tif_aux.Tpo -c tif_aux.c -o tif_aux.o
libtool: compile:  /workspace/CoFuzz/third_party/concolic/qsym/symcc -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_color.lo -MD -MP -MF .deps/tif_color.Tpo -c tif_color.c -o tif_color.o
libtool: compile:  /workspace/CoFuzz/third_party/concolic/qsym/symcc -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_close.lo -MD -MP -MF .deps/tif_close.Tpo -c tif_close.c -o tif_close.o
libtool: compile:  /workspace/CoFuzz/third_party/concolic/qsym/symcc -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_compress.lo -MD -MP -MF .deps/tif_compress.Tpo -c tif_compress.c -o tif_compress.o
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Stack dump:
0.  Program arguments: /usr/lib/llvm-10/bin/clang -Xclang -load -Xclang /workspace/CoFuzz/third_party/concolic/qsym/libSymbolize.so -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_close.lo -MD -MP -MF .deps/tif_close.Tpo -c tif_close.c -o tif_close.o -L/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -lSymRuntime -Wl,-rpath,/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -Qunused-arguments 
1.  <eof> parser at end of file
2.  Per-module optimization passes
3.  Running pass 'Function Pass Manager' on module 'tif_close.c'.
4.  Running pass 'Symbolization Pass' on function '@TIFFCleanup'
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Stack dump:
0.      Program arguments: /usr/lib/llvm-10/bin/clang -Xclang -load -Xclang /workspace/CoFuzz/third_party/concolic/qsym/libSymbolize.so -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_color.lo -MD -MP -MF .deps/tif_color.Tpo -c tif_color.c -o tif_color.o -L/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -lSymRuntime -Wl,-rpath,/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -Qunused-arguments 
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'Function Pass Manager' on module 'tif_color.c'.
4.      Running pass 'Symbolization Pass' on function '@TIFFCIELabToRGBInit'
Warning: unhandled LLVM intrinsic llvm.umul.with.overflow.i32; the result will be concretized
Warning: unhandled LLVM intrinsic llvm.umul.with.overflow.i64; the result will be concretized
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Stack dump:
0.      Program arguments: /usr/lib/llvm-10/bin/clang -Xclang -load -Xclang /workspace/CoFuzz/third_party/concolic/qsym/libSymbolize.so -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_aux.lo -MD -MP -MF .deps/tif_aux.Tpo -c tif_aux.c -o tif_aux.o -L/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -lSymRuntime -Wl,-rpath,/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -Qunused-arguments 
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'Function Pass Manager' on module 'tif_aux.c'.
4.      Running pass 'Symbolization Pass' on function '@_TIFFCheckMalloc'
terminate called after throwing an instance of 'std::out_of_range'
  what():  _Map_base::at
Stack dump:
0.      Program arguments: /usr/lib/llvm-10/bin/clang -Xclang -load -Xclang /workspace/CoFuzz/third_party/concolic/qsym/libSymbolize.so -DHAVE_CONFIG_H -I. -g -O2 -Wall -W -MT tif_compress.lo -MD -MP -MF .deps/tif_compress.Tpo -c tif_compress.c -o tif_compress.o -L/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -lSymRuntime -Wl,-rpath,/workspace/CoFuzz/third_party/concolic/qsym/SymRuntime-prefix/src/SymRuntime-build -Qunused-arguments 
1.      <eof> parser at end of file
2.      Per-module optimization passes
3.      Running pass 'Function Pass Manager' on module 'tif_compress.c'.
4.      Running pass 'Symbolization Pass' on function '@_TIFFNoRowEncode'
 #0 0x00007fe3aa7424ff llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x9814ff)
 #1 0x00007fe3aa7407b0 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x97f7b0)
 #2 0x00007fe3aa741c4d llvm::sys::CleanupOnSignal(unsigned long) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x980c4d)
 #3 0x00007fe3aa697e60 (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6e60)
 #4 0x00007fe3b0f11420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007fe3a98c400b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #6 0x00007fe3a98a3859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #7 0x00007fe3a9c7d8d1 (/lib/x86_64-linux-gnu/libstdc++.so.6+0x9e8d1)
 #8 0x00007fe3a9c8937c (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa37c)
 #9 0x00007fe3a9c893e7 (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa3e7)
#10 0x00007fe3a9c89699 (/lib/x86_64-linux-gnu/libstdc++.so.6+0xaa699)
#11 0x00007fe3a9c8033c std::__throw_out_of_range(char const*) (/lib/x86_64-linux-gnu/libstdc++.so.6+0xa133c)
#12 0x00007fe3a9783989 llvm::TrackingMDRef::~TrackingMDRef() /usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h:55:22
#13 0x00007fe3a9783989 llvm::TypedTrackingMDRef<llvm::MDNode>::~TypedTrackingMDRef() /usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h:106:26
#14 0x00007fe3a9783989 llvm::DebugLoc::~DebugLoc() /usr/lib/llvm-10/include/llvm/IR/DebugLoc.h:33:9
#15 0x00007fe3a9783989 llvm::IRBuilderBase::~IRBuilderBase() /usr/lib/llvm-10/include/llvm/IR/IRBuilder.h:88:7
#16 0x00007fe3a9783989 Symbolizer::visitBranchInst(llvm::BranchInst&) /workspace/CoFuzz/third_party/concolic/qsym/../compiler/Symbolizer.cpp:433:1
#17 0x00007fe3a978b45c SymbolizePass::runOnFunction(llvm::Function&) /workspace/CoFuzz/third_party/concolic/qsym/../compiler/Pass.cpp:94:22
#18 0x00007fe3aa847d76 llvm::FPPassManager::runOnFunction(llvm::Function&) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa86d76)
#19 0x00007fe3aa847ff3 llvm::FPPassManager::runOnModule(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa86ff3)
#20 0x00007fe3aa8484a0 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa874a0)
#21 0x00007fe3af83d3a9 clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x13e83a9)
#22 0x00007fe3afabce1c (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1667e1c)
#23 0x00007fe3aecaac13 clang::ParseAST(clang::Sema&, bool, bool) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x855c13)
#24 0x00007fe3b0120e58 clang::FrontendAction::Execute() (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1ccbe58)
#25 0x00007fe3b00d98a1 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1c848a1)
#26 0x00007fe3b0184daf clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1d2fdaf)
#27 0x000000000041229d cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/lib/llvm-10/bin/clang+0x41229d)
#28 0x00000000004105b1 (/usr/lib/llvm-10/bin/clang+0x4105b1)
#29 0x00007fe3afe2a8f2 (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19d58f2)
#30 0x00007fe3aa697c67 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6c67)
#31 0x00007fe3afe29e2f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19d4e2f)
#32 0x00007fe3afe0252f clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19ad52f)
#33 0x00007fe3afe026da clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19ad6da)
#34 0x00007fe3afe1593c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19c093c)
#35 0x000000000041002f main (/usr/lib/llvm-10/bin/clang+0x41002f)
#36 0x00007fe3a98a5083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#37 0x000000000040d7ce _start (/usr/lib/llvm-10/bin/clang+0x40d7ce)
clang: **erro**r: clang frontend command failed due to signal (use -v to see invocation)
clang version 10.0.0-4ubuntu1 
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm-10/bin
clang: note: diagnostic msg: PLEASE submit a bug report to https://bugs.llvm.org/ and include the crash backtrace, preprocessed source, and associated run script.
 #0 0x00007f31dea874ff llvm::sys::PrintStackTrace(llvm::raw_ostream&) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x9814ff)
 #1 0x00007f31dea857b0 llvm::sys::RunSignalHandlers() (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x97f7b0)
 #2 0x00007f31dea86c4d llvm::sys::CleanupOnSignal(unsigned long) (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x980c4d)
 #3 0x00007f31de9dce60 (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0x8d6e60)
 #4 0x00007f31e5256420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #5 0x00007f31ddc0900b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #6 0x00007f31ddbe8859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859) 
#0  #70x00007fdd402304ff   0x00007f31ddfc28d1#0llvm::sys::PrintStackTrace(llvm::raw_ostream&)   0x00007fb7b1dff4ff(( /lib/x86_64-linux-gnu/libstdc++.so.6/lib/x86_64-linux-gnu/libLLVM-10.so.1llvm::sys::PrintStackTrace(llvm::raw_ostream&)++ 0x9e8d10x9814ff())/lib/x86_64-linux-gnu/libLLVM-10.so.1

+  0x9814ff#8#1)  
0x00007f31ddfce37c0x00007fdd4022e7b0   (#1llvm::sys::RunSignalHandlers()/lib/x86_64-linux-gnu/libstdc++.so.6  +0x00007fb7b1dfd7b0(0xaa37c /lib/x86_64-linux-gnu/libLLVM-10.so.1)llvm::sys::RunSignalHandlers()+
 0x97f7b0( )/lib/x86_64-linux-gnu/libLLVM-10.so.1#9
+  0x00007f31ddfce3e70x97f7b0#2)  
(0x00007fdd4022fc4d /lib/x86_64-linux-gnu/libstdc++.so.6 #2+llvm::sys::CleanupOnSignal(unsigned long) 0xaa3e7 0x00007fb7b1dfec4d)( 
/lib/x86_64-linux-gnu/libLLVM-10.so.1llvm::sys::CleanupOnSignal(unsigned long)#10+  0x980c4d(0x00007f31ddfce699)/lib/x86_64-linux-gnu/libLLVM-10.so.1 
+( 0x980c4d/lib/x86_64-linux-gnu/libstdc++.so.6#3)+ 
0xaa6990x00007fdd40185e60 ) #3
( /lib/x86_64-linux-gnu/libLLVM-10.so.1#110x00007fb7b1d54e60+  0x8d6e600x00007f31ddfc533c() /lib/x86_64-linux-gnu/libLLVM-10.so.1
std::__throw_out_of_range(char const*)+  0x8d6e60#4() /lib/x86_64-linux-gnu/libstdc++.so.6
0x00007fdd469ff420+  0xa133c#4__restore_rt)  
0x00007fb7b85ce420(#12 /lib/x86_64-linux-gnu/libpthread.so.0 __restore_rt+0x00007f31ddac8974 0x14420 ()std::__detail::_Map_base<llvm::BasicBlock*, std::pair<llvm::BasicBlock* const, unsigned int>, std::allocator<std::pair<llvm::BasicBlock* const, unsigned int> >, std::__detail::_Select1st, std::equal_to<llvm::BasicBlock*>, std::hash<llvm::BasicBlock*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at(llvm::BasicBlock* const&)/lib/x86_64-linux-gnu/libpthread.so.0
 + /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/hashtable_policy.h:749:120x14420#5
) 
#130x00007fdd3f3b200b   #50x00007f31ddac8974raise   0x00007fb7b0f8100bstd::unordered_map<llvm::BasicBlock*, unsigned int, std::hash<llvm::BasicBlock*>, std::equal_to<llvm::BasicBlock*>, std::allocator<std::pair<llvm::BasicBlock* const, unsigned int> > >::at(llvm::BasicBlock* const&)(  /lib/x86_64-linux-gnu/libc.so.6raise/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unordered_map.h:1003:21+ 
0x4300b(#14)/lib/x86_64-linux-gnu/libc.so.6 0x00007f31ddac8974 Symbolizer::visitBranchInst(llvm::BranchInst&)
+  0x4300b/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Symbolizer.cpp:430:45#6)
 
#150x00007fdd3f391859   0x00007f31ddad045c#6abort   SymbolizePass::runOnFunction(llvm::Function&)0x00007fb7b0f60859(  /lib/x86_64-linux-gnu/libc.so.6/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Pass.cpp:94:22abort+ 
0x22859(#16)/lib/x86_64-linux-gnu/libc.so.6 
+0x00007f31deb8cd76 0x22859 )#7llvm::FPPassManager::runOnFunction(llvm::Function&)
   0x00007fdd3f76b8d1(#7 /lib/x86_64-linux-gnu/libLLVM-10.so.1 (+0x00007fb7b133a8d1/lib/x86_64-linux-gnu/libstdc++.so.60xa86d76 +)(0x9e8d1
/lib/x86_64-linux-gnu/libstdc++.so.6)#17+
 0x9e8d1 0x00007f31deb8cff3)#8 
 llvm::FPPassManager::runOnModule(llvm::Module&) 0x00007fdd3f77737c #8 ( (/lib/x86_64-linux-gnu/libLLVM-10.so.10x00007fb7b134637c/lib/x86_64-linux-gnu/libstdc++.so.6+ +0xa86ff3(0xaa37c)/lib/x86_64-linux-gnu/libstdc++.so.6)
+
#180xaa37c  )#90x00007f31deb8d4a0
   0x00007fdd3f7773e7 llvm::legacy::PassManagerImpl::run(llvm::Module&)#9(  /lib/x86_64-linux-gnu/libstdc++.so.6(0x00007fb7b13463e7+/lib/x86_64-linux-gnu/libLLVM-10.so.1 0xaa3e7+()0xa874a0/lib/x86_64-linux-gnu/libstdc++.so.6
)+#10
0xaa3e7 #19)0x00007fdd3f777699 
 0x00007f31e3b823a9#10(  /lib/x86_64-linux-gnu/libstdc++.so.6clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >)0x00007fb7b1346699+  0xaa699(()/lib/x86_64-linux-gnu/libclang-cpp.so.10/lib/x86_64-linux-gnu/libstdc++.so.6
++#110x13e83a90xaa699 ))0x00007fdd3f76e33c

 #20std::__throw_out_of_range(char const*)#11   0x00007f31e3e01e1c(0x00007fb7b133d33c /lib/x86_64-linux-gnu/libstdc++.so.6 (+std::__throw_out_of_range(char const*)/lib/x86_64-linux-gnu/libclang-cpp.so.100xa133c +)(0x1667e1c
/lib/x86_64-linux-gnu/libstdc++.so.6)#12+
 0xa133c#210x00007fdd3f271974 ) std::__detail::_Map_base<llvm::BasicBlock*, std::pair<llvm::BasicBlock* const, unsigned int>, std::allocator<std::pair<llvm::BasicBlock* const, unsigned int> >, std::__detail::_Select1st, std::equal_to<llvm::BasicBlock*>, std::hash<llvm::BasicBlock*>, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<false, false, true>, true>::at(llvm::BasicBlock* const&)
0x00007f31e2fefc13 #12 /usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/hashtable_policy.h:749:12 clang::ParseAST(clang::Sema&, bool, bool)
0x00007fb7b0e40989 #13 ( llvm::TrackingMDRef::~TrackingMDRef()/lib/x86_64-linux-gnu/libclang-cpp.so.100x00007fdd3f271974 + /usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h:55:220x855c13std::unordered_map<llvm::BasicBlock*, unsigned int, std::hash<llvm::BasicBlock*>, std::equal_to<llvm::BasicBlock*>, std::allocator<std::pair<llvm::BasicBlock* const, unsigned int> > >::at(llvm::BasicBlock* const&)
) #13
/usr/bin/../lib/gcc/x86_64-linux-gnu/9/../../../../include/c++/9/bits/unordered_map.h:1003:21 #22
0x00007fb7b0e40989 #14 0x00007f31e4465e58 llvm::TypedTrackingMDRef<llvm::MDNode>::~TypedTrackingMDRef() 0x00007fdd3f271974 clang::FrontendAction::Execute() /usr/lib/llvm-10/include/llvm/IR/TrackingMDRef.h:106:26 Symbolizer::visitBranchInst(llvm::BranchInst&)
( #14/lib/x86_64-linux-gnu/libclang-cpp.so.10/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Symbolizer.cpp:430:45 +
0x00007fb7b0e409890x1ccbe58#15 ) llvm::DebugLoc::~DebugLoc()
0x00007fdd3f27945c #23 /usr/lib/llvm-10/include/llvm/IR/DebugLoc.h:33:9 SymbolizePass::runOnFunction(llvm::Function&)0x00007f31e441e8a1  
#15/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Pass.cpp:94:22clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) 
 0x00007fb7b0e40989#16(  /lib/x86_64-linux-gnu/libclang-cpp.so.10llvm::IRBuilderBase::~IRBuilderBase()0x00007fdd40335d76+  0x1c848a1/usr/lib/llvm-10/include/llvm/IR/IRBuilder.h:88:7llvm::FPPassManager::runOnFunction(llvm::Function&))
 
(#16#24/lib/x86_64-linux-gnu/libLLVM-10.so.1  +0x00007fb7b0e409890x00007f31e44c9daf0xa86d76  )Symbolizer::visitBranchInst(llvm::BranchInst&)clang::ExecuteCompilerInvocation(clang::CompilerInstance*)
  #17/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Symbolizer.cpp:433:1( 
/lib/x86_64-linux-gnu/libclang-cpp.so.100x00007fdd40335ff3#17 + 0x00007fb7b0e4845c0x1d2fdafllvm::FPPassManager::runOnModule(llvm::Module&) ) SymbolizePass::runOnFunction(llvm::Function&)
( #25/lib/x86_64-linux-gnu/libLLVM-10.so.1/workspace/CoFuzz/third_party/concolic/qsym/../compiler/Pass.cpp:94:22 +
0x000000000041229d 0xa86ff3#18cc1_main(llvm::ArrayRef<char const*>, char const*, void*))  
0x00007fb7b1f04d76(#18 /usr/lib/llvm-10/bin/clang llvm::FPPassManager::runOnFunction(llvm::Function&)+0x00007fdd403364a0 0x41229d ()llvm::legacy::PassManagerImpl::run(llvm::Module&)/lib/x86_64-linux-gnu/libLLVM-10.so.1
 +#26(0xa86d76 /lib/x86_64-linux-gnu/libLLVM-10.so.1)0x00000000004105b1+
 0xa874a0#19() /usr/lib/llvm-10/bin/clang
0x00007fb7b1f04ff3+#190x4105b1  )llvm::FPPassManager::runOnModule(llvm::Module&)0x00007fdd4532b3a9
  #27(clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >) /lib/x86_64-linux-gnu/libLLVM-10.so.1 0x00007f31e416f8f2+( 0xa86ff3/lib/x86_64-linux-gnu/libclang-cpp.so.10()+/lib/x86_64-linux-gnu/libclang-cpp.so.10
0x13e83a9#20+) 0x19d58f2
0x00007fb7b1f054a0#20)  
llvm::legacy::PassManagerImpl::run(llvm::Module&)0x00007fdd455aae1c#28 (/lib/x86_64-linux-gnu/libLLVM-10.so.1+0xa874a0)
#21   (0x00007f31de9dcc670x00007fb7b6efa3a9/lib/x86_64-linux-gnu/libclang-cpp.so.10  +llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>)clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::DataLayout const&, llvm::Module*, clang::BackendAction, std::unique_ptr<llvm::raw_pwrite_stream, std::default_delete<llvm::raw_pwrite_stream> >)0x1667e1c  )((
/lib/x86_64-linux-gnu/libclang-cpp.so.10#21+ 0x13e83a90x00007fdd44798c13) /lib/x86_64-linux-gnu/libLLVM-10.so.1
clang::ParseAST(clang::Sema&, bool, bool)+#22 0x8d6c67 ()0x00007fb7b7179e1c/lib/x86_64-linux-gnu/libclang-cpp.so.10
 (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x1667e1c)
+#29#230x855c13  )0x00007f31e416ee2f0x00007fb7b6367c13
  #22clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) constclang::ParseAST(clang::Sema&, bool, bool)   0x00007fdd45c0ee58(( /lib/x86_64-linux-gnu/libclang-cpp.so.10/lib/x86_64-linux-gnu/libclang-cpp.so.10clang::FrontendAction::Execute()++ 0x19d4e2f0x855c13()
)/lib/x86_64-linux-gnu/libclang-cpp.so.10#30
+ #240x1ccbe580x00007f31e414752f ) 0x00007fb7b77dde58
clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const #23 clang::FrontendAction::Execute() ( 0x00007fdd45bc78a1/lib/x86_64-linux-gnu/libclang-cpp.so.10( +/lib/x86_64-linux-gnu/libclang-cpp.so.10clang::CompilerInstance::ExecuteAction(clang::FrontendAction&)0x19ad52f+ )0x1ccbe58(
)#31/lib/x86_64-linux-gnu/libclang-cpp.so.10
 +#250x00007f31e41476da0x1c848a1  )0x00007fb7b77968a1clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const
  clang::CompilerInstance::ExecuteAction(clang::FrontendAction&)#24(  /lib/x86_64-linux-gnu/libclang-cpp.so.10(0x00007fdd45c72daf+/lib/x86_64-linux-gnu/libclang-cpp.so.10 0x19ad6da+clang::ExecuteCompilerInvocation(clang::CompilerInstance*))0x1c848a1)
#26 
 (0x00007fb7b7841daf#32/lib/x86_64-linux-gnu/libclang-cpp.so.10  +clang::ExecuteCompilerInvocation(clang::CompilerInstance*)0x00007f31e415a93c0x1d2fdaf  )(clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&)
/lib/x86_64-linux-gnu/libclang-cpp.so.10 #25+( 0x1d2fdaf/lib/x86_64-linux-gnu/libclang-cpp.so.100x000000000041229d)+ 
0x19c093ccc1_main(llvm::ArrayRef<char const*>, char const*, void*)#27)  
(#330x000000000041229d/usr/lib/llvm-10/bin/clang  +0x000000000041002fcc1_main(llvm::ArrayRef<char const*>, char const*, void*)0x41229d  )main(
 /usr/lib/llvm-10/bin/clang#26(+ /usr/lib/llvm-10/bin/clang0x41229d0x00000000004105b1+) 0x41002f
(#28)/usr/lib/llvm-10/bin/clang 
+0x00000000004105b1#340x4105b1  )(0x00007f31ddbea083
/usr/lib/llvm-10/bin/clang +#27__libc_start_main0x4105b1  )0x00007fdd459188f2(
 /lib/x86_64-linux-gnu/libc.so.6#29(+ /lib/x86_64-linux-gnu/libclang-cpp.so.100x240830x00007fb7b74e78f2+) (/lib/x86_64-linux-gnu/libclang-cpp.so.10+0x19d58f2)
0x19d58f2
#30)#35 
 0x00007fb7b1d54c67#280x000000000040d7ce   llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>)0x00007fdd40185c67_start   (llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>)(/lib/x86_64-linux-gnu/libLLVM-10.so.1 /usr/lib/llvm-10/bin/clang+(+0x8d6c67/lib/x86_64-linux-gnu/libLLVM-10.so.10x40d7ce)+)
0x8d6c67
#31) 
0x00007fb7b74e6e2f clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const#29  (0x00007fdd45917e2f/lib/x86_64-linux-gnu/libclang-cpp.so.10 +clang::driver::CC1Command::Execute(llvm::ArrayRef<llvm::Optional<llvm::StringRef> >, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*) const0x19d4e2f )(
/lib/x86_64-linux-gnu/libclang-cpp.so.10#32+ 0x19d4e2f0x00007fb7b74bf52f) 
clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const#30  (0x00007fdd458f052f/lib/x86_64-linux-gnu/libclang-cpp.so.10+ 0x19ad52fclang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&) const) 
(#33/lib/x86_64-linux-gnu/libclang-cpp.so.10 +0x00007fb7b74bf6da0x19ad52f )clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const
 #31( /lib/x86_64-linux-gnu/libclang-cpp.so.100x00007fdd458f06da+ 0x19ad6daclangclang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) const):  
#34 0x00007fb7b74d293c clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*> >&) ((**/lib/x86_64-linux-gnu/libclang-cpp.so.10/lib/x86_64-linux-gnu/libclang-cpp.so.10error++: 0x19c093c0x19ad6da**))clang frontend command failed due to signal (use -v to see invocation)

Is my libc version wrong?

**Comment by Tricker-z** [comment]
Hi, could you please use the Dockerfile https://github.com/Tricker-z/CoFuzz/blob/main/Dockerfile and try it again, it seems that the issue of env

**Comment by kittener** [comment]
In fact, I recompiled with this Dockerfile [https://github.com/Tricker-z/symcc/blob/3d8721065ac1516eb1d9c316935aa4b93312bab2/Dockerfile](https://github.com/Tricker-z/symcc/blob/3d8721065ac1516eb1d9c316935aa4b93312bab2/Dockerfile) and it worked. Can the compiled file be used by cofuzz?

**Comment by Tricker-z** [comment]
If you're using symcc from cofuzz, it's theoretically possible.
